name: Build and Publish

on:
  workflow_dispatch:
  pull_request:
  release:
    types:
    - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install hatch
      run: pipx install hatch
    - name: Build sdist and wheel
      run: hatch build --clean
    - name: Publish
      if: github.event_name == 'release' && github.event.action == 'published'
      run: hatch publish --user __token__ --auth ${{ secrets.pypi_password }}
  conda-build:
    runs-on: ubuntu-latest
    needs: [build]
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
    - name: Install conda-build
      run: |
        conda install -y conda-build
    - name: Create conda package
      run: |
        bash scripts/conda-build.sh
